### ISSUE TITLE
Can't build with rustc 1.36.0-nightly (7c71bc320 2019-04-30)

### ISSUE THREAD

**Issue by updogliu** [rustasync/tide#197]
#### Environment

- Rust toolchain version(s): nightly-x86_64-unknown-linux-gnu, rustc 1.36.0-nightly (7c71bc320 2019-04-30)
- OS: Ubuntu 16.04

#### Possible Solution
Update dependency versions of `http-service`, `http-service-hyper`, `http-service-mock` to 0.2.0

#### Build Error
```
   Compiling http-service v0.1.5
error[E0432]: unresolved import `futures::stream::StreamObj`
  --> /home/updogliu/.cargo/registry/src/github.com-1ecc6299db9ec823/http-service-0.1.5/src/lib.rs:14:20
   |
14 |     stream::{self, StreamObj},
   |                    ^^^^^^^^^
   |                    |
   |                    no `StreamObj` in `stream`
   |                    help: a similar name exists in the module: `StreamExt`

error[E0599]: no method named `poll_next` found for type `std::pin::Pin<_>` in the current scope
  --> /home/updogliu/.cargo/registry/src/github.com-1ecc6299db9ec823/http-service-0.1.5/src/lib.rs:69:36
   |
69 |         Pin::new(&mut self.stream).poll_next(cx)
   |                                    ^^^^^^^^^
   |
   = note: Pin::new(&mut self.stream) is a function, perhaps you wish to call it

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
error: Could not compile `http-service`.
```

**Comment by secretfader** [comment]
Tide is lacking a few updates (like #193) that are needed to build on the latest `nightly`. Until we sync up with the latest `std::futures` API, please refer to the `README` for supported versions of `rustc`.
