### ISSUE TITLE
Can't build with rustc 1.36.0-nightly (3f5152e20 2019-05-08)

### ISSUE THREAD

**Issue by k-nasa** [rustasync/tide#237]
## Question
Help me!
Why can't this be built?
I did not know the cause...

## Additional context
Cargo.toml
```Cargo.toml
[package]
name = "tide_example"
version = "0.1.0"
authors = ["k-nasa <htilcs1115@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tide = { git = "https://github.com/rustasync/tide" }
```
```console
cargo build
   Compiling tide v0.2.0 (https://github.com/rustasync/tide#bdc9fdf0)
error[E0437]: type `ResponseFuture` is not a member of trait `HttpService`
   --> /Users/nasa/.cargo/git/checkouts/tide-d8df193c9a60972c/bdc9fdf/tide/src/app.rs:281:5
    |
281 |     type ResponseFuture = BoxFuture<'static, Result<http_service::Response, std::io::Error>>;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a member of trait `HttpService`

error[E0220]: associated type `ResponseFuture` not found for `Self`
   --> /Users/nasa/.cargo/git/checkouts/tide-d8df193c9a60972c/bdc9fdf/tide/src/app.rs:287:70
    |
287 |     fn respond(&self, _conn: &mut (), req: http_service::Request) -> Self::ResponseFuture {
    |                                                                      ^^^^^^^^^^^^^^^^^^^^ associated type `ResponseFuture` not found

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0220, E0437.
For more information about an error, try `rustc --explain E0220`.
error: Could not compile `tide`.

To learn more, run the command again with --verbose.
```

**Comment by taiki-e** [comment]
Add these to your `Cargo.toml` and they should be fixed.
```toml
[patch.crates-io]
http-service = { git = "https://github.com/rustasync/http-service", branch = "master" }
http-service-hyper = { git = "https://github.com/rustasync/http-service", branch = "master" }
http-service-mock = { git = "https://github.com/rustasync/http-service", branch = "master" }
```

**Comment by k-nasa** [comment]
@taiki-e I could build! Thank you
